# Generated by Django 5.2.7 on 2025-10-04 16:08

from django.db import migrations


def fix_user_roles(apps, schema_editor):
    """
    Исправляет роли пользователей, заменяя несуществующую роль 'user' на 'viewer'
    """
    User = apps.get_model('users', 'User')
    
    # Заменяем роль 'user' на 'viewer' для всех пользователей
    User.objects.filter(role='user').update(role='viewer')


def reverse_fix_user_roles(apps, schema_editor):
    """
    Обратная операция - заменяет 'viewer' обратно на 'user'
    """
    User = apps.get_model('users', 'User')
    
    # Заменяем роль 'viewer' обратно на 'user' (если нужно откатить)
    User.objects.filter(role='viewer').update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_user_roles, reverse_fix_user_roles),
    ]