# Generated by Django 5.2.7 on 2025-10-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='WARA', max_length=100, verbose_name='Название приложения')),
                ('app_description', models.TextField(default='Система анализа документов', verbose_name='Описание приложения')),
                ('max_file_size', models.PositiveIntegerField(default=10485760, verbose_name='Максимальный размер файла (байты)')),
                ('allowed_file_types', models.TextField(default='docx,pdf', verbose_name='Разрешенные типы файлов (через запятую)')),
                ('auto_analysis_enabled', models.BooleanField(default=True, verbose_name='Автоматический анализ включен')),
                ('analysis_timeout', models.PositiveIntegerField(default=300, verbose_name='Таймаут анализа (секунды)')),
                ('auto_reports_enabled', models.BooleanField(default=True, verbose_name='Автоматическая генерация отчетов включена')),
                ('default_report_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], default='pdf', max_length=10, verbose_name='Формат отчета по умолчанию')),
                ('email_notifications_enabled', models.BooleanField(default=False, verbose_name='Email уведомления включены')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений')),
                ('session_timeout', models.PositiveIntegerField(default=3600, verbose_name='Таймаут сессии (секунды)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, verbose_name='Максимальное количество попыток входа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
    ]
