# Generated by Django 5.2.7 on 2025-10-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='WARA Server', max_length=100, verbose_name='Название сервера')),
                ('server_description', models.TextField(default='Сервер системы анализа документов WARA', verbose_name='Описание сервера')),
                ('max_concurrent_requests', models.PositiveIntegerField(default=100, verbose_name='Максимальное количество одновременных запросов')),
                ('request_timeout', models.PositiveIntegerField(default=30, verbose_name='Таймаут запросов (секунды)')),
                ('max_memory_usage', models.PositiveIntegerField(default=2048, verbose_name='Максимальное использование памяти (МБ)')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=10, verbose_name='Уровень логирования')),
                ('log_retention_days', models.PositiveIntegerField(default=30, verbose_name='Срок хранения логов (дни)')),
                ('enable_access_log', models.BooleanField(default=True, verbose_name='Включить логирование доступа')),
                ('enable_cache', models.BooleanField(default=True, verbose_name='Включить кэширование')),
                ('cache_timeout', models.PositiveIntegerField(default=300, verbose_name='Таймаут кэша (секунды)')),
                ('max_cache_size', models.PositiveIntegerField(default=100, verbose_name='Максимальный размер кэша (МБ)')),
                ('enable_rate_limiting', models.BooleanField(default=True, verbose_name='Включить ограничение частоты запросов')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, verbose_name='Лимит запросов в минуту')),
                ('enable_csrf_protection', models.BooleanField(default=True, verbose_name='Включить защиту от CSRF')),
                ('session_cookie_secure', models.BooleanField(default=False, verbose_name='Безопасные cookies сессии')),
                ('enable_health_check', models.BooleanField(default=True, verbose_name='Включить проверку здоровья сервера')),
                ('health_check_interval', models.PositiveIntegerField(default=60, verbose_name='Интервал проверки здоровья (секунды)')),
                ('enable_metrics', models.BooleanField(default=True, verbose_name='Включить сбор метрик')),
                ('enable_backup', models.BooleanField(default=True, verbose_name='Включить автоматическое резервное копирование')),
                ('backup_interval_hours', models.PositiveIntegerField(default=24, verbose_name='Интервал резервного копирования (часы)')),
                ('backup_retention_days', models.PositiveIntegerField(default=30, verbose_name='Срок хранения резервных копий (дни)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Настройки сервера',
                'verbose_name_plural': 'Настройки сервера',
            },
        ),
    ]
