# Generated by Django 5.2.7 on 2025-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_serversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='items_per_page',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество элементов на странице'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='app_name',
            field=models.CharField(default='Document analyzer', max_length=100, verbose_name='Название приложения'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='server_description',
            field=models.TextField(default='Сервер системы анализа документов Document analyzer', verbose_name='Описание сервера'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='server_name',
            field=models.CharField(default='Document analyzer Server', max_length=100, verbose_name='Название сервера'),
        ),
    ]
