# Generated by Django 5.2.7 on 2025-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_applicationsettings_items_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='default_neural_network_model',
            field=models.CharField(default='llama3', max_length=100, verbose_name='Модель нейросети по умолчанию'),
        ),
    ]
