# Generated by Django 5.2.7 on 2025-10-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_applicationsettings_default_neural_network_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_client_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID клиента Microsoft (Client ID)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_client_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='Секрет клиента Microsoft (Client Secret)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_drive_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID диска SharePoint'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_folder_path',
            field=models.CharField(blank=True, default='/Documents', max_length=500, verbose_name='Путь к папке в SharePoint'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_graph_enabled',
            field=models.BooleanField(default=False, verbose_name='Интеграция с Microsoft Graph включена'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_redirect_uri',
            field=models.URLField(blank=True, default='http://localhost:8000/auth/microsoft/callback/', verbose_name='URI перенаправления Microsoft'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_scope',
            field=models.TextField(default='https://graph.microsoft.com/Files.Read https://graph.microsoft.com/Sites.Read.All', verbose_name='Области доступа Microsoft (Scope)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_site_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID сайта SharePoint'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_tenant_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID арендатора Microsoft (Tenant ID)'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='app_name',
            field=models.CharField(default='📊 Анализатор документов', max_length=100, verbose_name='Название приложения'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='server_description',
            field=models.TextField(default='Сервер системы анализа документов 📊 Анализатор документов', verbose_name='Описание сервера'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='server_name',
            field=models.CharField(default='📊 Анализатор документов Server', max_length=100, verbose_name='Название сервера'),
        ),
        migrations.CreateModel(
            name='MicrosoftGraphToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Токен доступа')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Токен обновления')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Тип токена')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('scope', models.TextField(verbose_name='Области доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен Microsoft Graph',
                'verbose_name_plural': 'Токены Microsoft Graph',
            },
        ),
    ]
