# Generated by Django 5.2.7 on 2025-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_applicationsettings_microsoft_client_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: update_microsoft_settings(apps, schema_editor),
            lambda apps, schema_editor: None,
        ),
    ]


def update_microsoft_settings(apps, schema_editor):
    """Обновить настройки Microsoft Graph значениями по умолчанию"""
    ApplicationSettings = apps.get_model('settings', 'ApplicationSettings')
    
    settings, created = ApplicationSettings.objects.get_or_create(
        defaults={
            'app_name': '📊 Анализатор документов',
            'app_description': 'Система анализа документов',
            'items_per_page': 10,
            'default_neural_network_model': 'llama3',
            'microsoft_graph_enabled': False,
            'microsoft_tenant_id': '',
            'microsoft_client_id': '',
            'microsoft_client_secret': '',
            'microsoft_redirect_uri': 'http://localhost:8000/auth/microsoft/callback/',
            'microsoft_scope': 'https://graph.microsoft.com/Files.Read https://graph.microsoft.com/Sites.Read.All',
            'microsoft_site_id': '',
            'microsoft_drive_id': '',
            'microsoft_folder_path': '/Documents',
        }
    )
    
    if not created:
        # Обновляем существующие настройки
        settings.microsoft_graph_enabled = False
        settings.microsoft_tenant_id = settings.microsoft_tenant_id or ''
        settings.microsoft_client_id = settings.microsoft_client_id or ''
        settings.microsoft_client_secret = settings.microsoft_client_secret or ''
        settings.microsoft_redirect_uri = settings.microsoft_redirect_uri or 'http://localhost:8000/auth/microsoft/callback/'
        settings.microsoft_scope = settings.microsoft_scope or 'https://graph.microsoft.com/Files.Read https://graph.microsoft.com/Sites.Read.All'
        settings.microsoft_site_id = settings.microsoft_site_id or ''
        settings.microsoft_drive_id = settings.microsoft_drive_id or ''
        settings.microsoft_folder_path = settings.microsoft_folder_path or '/Documents'
        settings.save()
