# Generated by Django 5.2.7 on 2025-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20251005_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_client_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID клиента AD (Client ID)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_client_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='Секрет клиента AD (Client Secret)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Домен Active Directory'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_enabled',
            field=models.BooleanField(default=False, verbose_name='Microsoft Active Directory SSO включен'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_redirect_uri',
            field=models.URLField(blank=True, default='http://localhost:8000/auth/microsoft/sso/callback/', verbose_name='URI перенаправления AD SSO'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_scope',
            field=models.TextField(default='https://graph.microsoft.com/User.Read https://graph.microsoft.com/Group.Read.All', verbose_name='Области доступа AD SSO (Scope)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_tenant_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID арендатора AD (Tenant ID)'),
        ),
    ]
