# Generated by Django 5.2.7 on 2025-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_applicationsettings_microsoft_ad_sso_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_certificate_thumbprint',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отпечаток сертификата'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_directory_service',
            field=models.CharField(choices=[('azure_ad', 'Azure Active Directory'), ('adfs', 'Active Directory Federation Services (ADFS)'), ('on_premises_ad', 'Локальный Active Directory'), ('hybrid_ad', 'Гибридная среда AD')], default='azure_ad', max_length=100, verbose_name='Тип службы каталогов'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_directory_url',
            field=models.URLField(blank=True, verbose_name='URL службы каталогов'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_issuer',
            field=models.URLField(blank=True, verbose_name='Издатель (Issuer)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_metadata_url',
            field=models.URLField(blank=True, verbose_name='URL метаданных'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_realm',
            field=models.CharField(blank=True, max_length=200, verbose_name='Область (Realm)'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='microsoft_ad_sso_saml_enabled',
            field=models.BooleanField(default=False, verbose_name='Использовать SAML'),
        ),
    ]
