# Generated by Django 5.2.7 on 2025-10-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Имя получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Email уведомление',
                'verbose_name_plural': 'Email уведомления',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Формат')),
                ('template_content', models.TextField(verbose_name='Содержимое шаблона')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Формат')),
                ('status', models.CharField(choices=[('generating', 'Генерируется'), ('ready', 'Готов'), ('sent', 'Отправлен'), ('error', 'Ошибка')], default='generating', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл отчета')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('template_used', models.CharField(default='default', max_length=100, verbose_name='Использованный шаблон')),
                ('include_summary', models.BooleanField(default=True, verbose_name='Включить сводку')),
                ('include_details', models.BooleanField(default=True, verbose_name='Включить детали')),
                ('include_tables', models.BooleanField(default=True, verbose_name='Включить таблицы')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('email_recipients', models.JSONField(blank=True, default=list, verbose_name='Получатели email')),
                ('summary_data', models.JSONField(blank=True, default=dict, verbose_name='Данные сводки')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Время генерации (сек)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analysis.comparison', verbose_name='Сравнение')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-generated_date'],
            },
        ),
    ]
