# Generated by Django 5.2.7 on 2025-10-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_latest_version',
            field=models.BooleanField(default=True, verbose_name='Последняя версия'),
        ),
        migrations.AddField(
            model_name='report',
            name='parent_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report', verbose_name='Родительский отчет'),
        ),
        migrations.AddField(
            model_name='report',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Версия отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='version_notes',
            field=models.TextField(blank=True, verbose_name='Заметки к версии'),
        ),
    ]
