# Generated by Django 5.2.7 on 2025-10-04 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Файл документа')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('checksum', models.CharField(max_length=64, verbose_name='Контрольная сумма')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обрабатывается'), ('processed', 'Обработан'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('content_text', models.TextField(blank=True, verbose_name='Текстовое содержимое')),
                ('content_structure', models.JSONField(blank=True, default=dict, verbose_name='Структура документа')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('content', models.TextField(verbose_name='Содержимое раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень заголовка')),
            ],
            options={
                'verbose_name': 'Раздел документа',
                'verbose_name_plural': 'Разделы документа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок таблицы')),
                ('data', models.JSONField(verbose_name='Данные таблицы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Таблица документа',
                'verbose_name_plural': 'Таблицы документа',
                'ordering': ['order'],
            },
        ),
    ]
