# Generated by Django 5.2.7 on 2025-10-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_latest_version',
            field=models.BooleanField(default=True, verbose_name='Последняя версия'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Родительский документ'),
        ),
        migrations.AddField(
            model_name='document',
            name='version_notes',
            field=models.TextField(blank=True, verbose_name='Заметки к версии'),
        ),
    ]
