# Generated by Django 5.2.7 on 2025-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_latest_version_document_parent_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='Ошибка обработки'),
        ),
    ]
