# Generated by Django 5.2.7 on 2025-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_processing_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key_points',
            field=models.JSONField(blank=True, default=list, verbose_name='Ключевые моменты'),
        ),
        migrations.AddField(
            model_name='document',
            name='key_points_generated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации ключевых моментов'),
        ),
    ]
