# Generated by Django 5.2.7 on 2025-10-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_key_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTableAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField(verbose_name='Количество строк')),
                ('column_count', models.PositiveIntegerField(verbose_name='Количество столбцов')),
                ('cell_count', models.PositiveIntegerField(verbose_name='Общее количество ячеек')),
                ('empty_cells_count', models.PositiveIntegerField(default=0, verbose_name='Количество пустых ячеек')),
                ('numeric_cells_count', models.PositiveIntegerField(default=0, verbose_name='Количество числовых ячеек')),
                ('text_cells_count', models.PositiveIntegerField(default=0, verbose_name='Количество текстовых ячеек')),
                ('has_headers', models.BooleanField(default=False, verbose_name='Есть заголовки')),
                ('header_row_count', models.PositiveIntegerField(default=0, verbose_name='Количество строк заголовков')),
                ('table_type', models.CharField(blank=True, max_length=100, verbose_name='Тип таблицы')),
                ('main_topic', models.CharField(blank=True, max_length=200, verbose_name='Основная тема')),
                ('key_metrics', models.JSONField(blank=True, default=list, verbose_name='Ключевые метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_analyses', to='documents.document', verbose_name='Документ')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.documenttable', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Анализ таблицы',
                'verbose_name_plural': 'Анализы таблиц',
                'ordering': ['-created_at'],
            },
        ),
    ]
