# Generated by Django 5.2.7 on 2025-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttableanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='formatted_content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Форматированное содержимое'),
        ),
    ]
