# Generated by Django 5.2.7 on 2025-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitivity', models.FloatField(default=0.8, verbose_name='Чувствительность к изменениям (0-1)')),
                ('include_text_changes', models.BooleanField(default=True, verbose_name='Анализировать изменения текста')),
                ('include_table_changes', models.BooleanField(default=True, verbose_name='Анализировать изменения таблиц')),
                ('include_structure_changes', models.BooleanField(default=True, verbose_name='Анализировать структурные изменения')),
                ('min_change_length', models.PositiveIntegerField(default=3, verbose_name='Минимальная длина изменения')),
            ],
            options={
                'verbose_name': 'Настройка анализа',
                'verbose_name_plural': 'Настройки анализа',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Добавлено'), ('removed', 'Удалено'), ('modified', 'Изменено'), ('moved', 'Перемещено')], max_length=20, verbose_name='Тип изменения')),
                ('location', models.CharField(choices=[('text', 'Текст'), ('table', 'Таблица'), ('section', 'Раздел'), ('header', 'Заголовок'), ('structure', 'Структура')], max_length=20, verbose_name='Местоположение')),
                ('section', models.CharField(blank=True, max_length=255, verbose_name='Раздел')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность (0-1)')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст изменения')),
            ],
            options={
                'verbose_name': 'Изменение',
                'verbose_name_plural': 'Изменения',
                'ordering': ['comparison', 'section', 'change_type'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сравнения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('changes_summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка изменений')),
                ('detailed_changes', models.JSONField(blank=True, default=list, verbose_name='Детальные изменения')),
            ],
            options={
                'verbose_name': 'Сравнение документов',
                'verbose_name_plural': 'Сравнения документов',
                'ordering': ['-created_date'],
            },
        ),
    ]
