# Generated by Django 5.2.7 on 2025-10-04 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='base_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comparisons', to='documents.document', verbose_name='Базовый документ'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='compared_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_comparisons', to='documents.document', verbose_name='Сравниваемый документ'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='change',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='analysis.comparison', verbose_name='Сравнение'),
        ),
        migrations.AlterUniqueTogether(
            name='analysissettings',
            unique_together={('user',)},
        ),
    ]
