# Generated by Django 5.2.7 on 2025-10-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='analysis_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Метод анализа'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='analysis_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат анализа'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='analysis_type',
            field=models.CharField(choices=[('diff', 'Сравнение различий'), ('ollama', 'Анализ нейросетью')], default='diff', max_length=20, verbose_name='Тип анализа'),
        ),
    ]
